<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-Q2RM1HI" failures="0" tests="40" name="testExample.Add_CustomerTest" time="0.046" errors="8" timestamp="2021-12-28T08:49:31 IST" skipped="32">
  <testcase classname="testExample.Add_CustomerTest" name="Clickcustomer" time="0.001">
    <skipped/>
  </testcase> <!-- Clickcustomer -->
  <testcase classname="testExample.Add_CustomerTest" name="Clickcustomer" time="0.000">
    <skipped/>
  </testcase> <!-- Clickcustomer -->
  <testcase classname="testExample.Add_CustomerTest" name="Clickcustomer" time="0.001">
    <skipped/>
  </testcase> <!-- Clickcustomer -->
  <testcase classname="testExample.Add_CustomerTest" name="Clickcustomer" time="0.002">
    <skipped/>
  </testcase> <!-- Clickcustomer -->
  <testcase classname="testExample.Add_CustomerTest" name="Clickcustomer" time="0.001">
    <skipped/>
  </testcase> <!-- Clickcustomer -->
  <testcase classname="testExample.Add_CustomerTest" name="Clickcustomer" time="0.001">
    <skipped/>
  </testcase> <!-- Clickcustomer -->
  <testcase classname="testExample.Add_CustomerTest" name="Clickcustomer" time="0.001">
    <skipped/>
  </testcase> <!-- Clickcustomer -->
  <testcase classname="testExample.Add_CustomerTest" name="Clickcustomer" time="0.001">
    <error message="Cannot invoke &quot;pageExample.Add_Customer.Click()&quot; because &quot;this.cust&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "pageExample.Add_Customer.Click()" because "this.cust" is null
at testExample.Add_CustomerTest.Clickcustomer(Add_CustomerTest.java:9)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:201)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at org.testng.TestRunner.privateRun(TestRunner.java:763)
at org.testng.TestRunner.run(TestRunner.java:594)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:41)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:437)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:67)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </error>
  </testcase> <!-- Clickcustomer -->
  <testcase classname="testExample.Add_CustomerTest" name="Clickcustomer" time="0.006">
    <error message="Cannot invoke &quot;pageExample.Add_Customer.Click()&quot; because &quot;this.cust&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "pageExample.Add_Customer.Click()" because "this.cust" is null
at testExample.Add_CustomerTest.Clickcustomer(Add_CustomerTest.java:9)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:201)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at org.testng.TestRunner.privateRun(TestRunner.java:763)
at org.testng.TestRunner.run(TestRunner.java:594)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:41)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:437)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:67)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </error>
  </testcase> <!-- Clickcustomer -->
  <testcase classname="testExample.Add_CustomerTest" name="Clickcustomer" time="0.001">
    <skipped/>
  </testcase> <!-- Clickcustomer -->
  <testcase classname="testExample.Add_CustomerTest" name="emailField" time="0.000">
    <skipped/>
  </testcase> <!-- emailField -->
  <testcase classname="testExample.Add_CustomerTest" name="emailField" time="0.001">
    <skipped/>
  </testcase> <!-- emailField -->
  <testcase classname="testExample.Add_CustomerTest" name="emailField" time="0.001">
    <skipped/>
  </testcase> <!-- emailField -->
  <testcase classname="testExample.Add_CustomerTest" name="emailField" time="0.002">
    <skipped/>
  </testcase> <!-- emailField -->
  <testcase classname="testExample.Add_CustomerTest" name="emailField" time="0.002">
    <skipped/>
  </testcase> <!-- emailField -->
  <testcase classname="testExample.Add_CustomerTest" name="emailField" time="0.001">
    <error message="Cannot invoke &quot;pageExample.Search_Customer.emailField(String)&quot; because &quot;this.se&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "pageExample.Search_Customer.emailField(String)" because "this.se" is null
at testExample.Add_CustomerTest.emailField(Add_CustomerTest.java:14)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:201)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at org.testng.TestRunner.privateRun(TestRunner.java:763)
at org.testng.TestRunner.run(TestRunner.java:594)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:41)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:437)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:67)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </error>
  </testcase> <!-- emailField -->
  <testcase classname="testExample.Add_CustomerTest" name="emailField" time="0.004">
    <error message="Cannot invoke &quot;pageExample.Search_Customer.emailField(String)&quot; because &quot;this.se&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "pageExample.Search_Customer.emailField(String)" because "this.se" is null
at testExample.Add_CustomerTest.emailField(Add_CustomerTest.java:14)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:201)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at org.testng.TestRunner.privateRun(TestRunner.java:763)
at org.testng.TestRunner.run(TestRunner.java:594)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:41)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:437)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:67)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </error>
  </testcase> <!-- emailField -->
  <testcase classname="testExample.Add_CustomerTest" name="emailField" time="0.001">
    <skipped/>
  </testcase> <!-- emailField -->
  <testcase classname="testExample.Add_CustomerTest" name="emailField" time="0.001">
    <skipped/>
  </testcase> <!-- emailField -->
  <testcase classname="testExample.Add_CustomerTest" name="emailField" time="0.000">
    <skipped/>
  </testcase> <!-- emailField -->
  <testcase classname="testExample.Add_CustomerTest" name="fnameField" time="0.001">
    <error message="Cannot invoke &quot;pageExample.Search_Customer.fnameField(String)&quot; because &quot;this.se&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "pageExample.Search_Customer.fnameField(String)" because "this.se" is null
at testExample.Add_CustomerTest.fnameField(Add_CustomerTest.java:21)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:201)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at org.testng.TestRunner.privateRun(TestRunner.java:763)
at org.testng.TestRunner.run(TestRunner.java:594)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:41)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:437)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:67)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </error>
  </testcase> <!-- fnameField -->
  <testcase classname="testExample.Add_CustomerTest" name="fnameField" time="0.000">
    <error message="Cannot invoke &quot;pageExample.Search_Customer.fnameField(String)&quot; because &quot;this.se&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "pageExample.Search_Customer.fnameField(String)" because "this.se" is null
at testExample.Add_CustomerTest.fnameField(Add_CustomerTest.java:21)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:201)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at org.testng.TestRunner.privateRun(TestRunner.java:763)
at org.testng.TestRunner.run(TestRunner.java:594)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:41)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:437)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:67)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </error>
  </testcase> <!-- fnameField -->
  <testcase classname="testExample.Add_CustomerTest" name="fnameField" time="0.001">
    <skipped/>
  </testcase> <!-- fnameField -->
  <testcase classname="testExample.Add_CustomerTest" name="fnameField" time="0.003">
    <skipped/>
  </testcase> <!-- fnameField -->
  <testcase classname="testExample.Add_CustomerTest" name="fnameField" time="0.001">
    <skipped/>
  </testcase> <!-- fnameField -->
  <testcase classname="testExample.Add_CustomerTest" name="fnameField" time="0.003">
    <skipped/>
  </testcase> <!-- fnameField -->
  <testcase classname="testExample.Add_CustomerTest" name="fnameField" time="0.001">
    <skipped/>
  </testcase> <!-- fnameField -->
  <testcase classname="testExample.Add_CustomerTest" name="fnameField" time="0.000">
    <skipped/>
  </testcase> <!-- fnameField -->
  <testcase classname="testExample.Add_CustomerTest" name="fnameField" time="0.000">
    <skipped/>
  </testcase> <!-- fnameField -->
  <testcase classname="testExample.Add_CustomerTest" name="fnameField" time="0.001">
    <skipped/>
  </testcase> <!-- fnameField -->
  <testcase classname="testExample.Add_CustomerTest" name="LnameField" time="0.001">
    <error message="Cannot invoke &quot;pageExample.Search_Customer.LnameField(String)&quot; because &quot;this.se&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "pageExample.Search_Customer.LnameField(String)" because "this.se" is null
at testExample.Add_CustomerTest.LnameField(Add_CustomerTest.java:27)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:201)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at org.testng.TestRunner.privateRun(TestRunner.java:763)
at org.testng.TestRunner.run(TestRunner.java:594)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:41)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:437)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:67)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </error>
  </testcase> <!-- LnameField -->
  <testcase classname="testExample.Add_CustomerTest" name="LnameField" time="0.001">
    <skipped/>
  </testcase> <!-- LnameField -->
  <testcase classname="testExample.Add_CustomerTest" name="LnameField" time="0.001">
    <skipped/>
  </testcase> <!-- LnameField -->
  <testcase classname="testExample.Add_CustomerTest" name="LnameField" time="0.001">
    <skipped/>
  </testcase> <!-- LnameField -->
  <testcase classname="testExample.Add_CustomerTest" name="LnameField" time="0.001">
    <error message="Cannot invoke &quot;pageExample.Search_Customer.LnameField(String)&quot; because &quot;this.se&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "pageExample.Search_Customer.LnameField(String)" because "this.se" is null
at testExample.Add_CustomerTest.LnameField(Add_CustomerTest.java:27)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:201)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at org.testng.TestRunner.privateRun(TestRunner.java:763)
at org.testng.TestRunner.run(TestRunner.java:594)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:41)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:437)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:67)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </error>
  </testcase> <!-- LnameField -->
  <testcase classname="testExample.Add_CustomerTest" name="LnameField" time="0.000">
    <skipped/>
  </testcase> <!-- LnameField -->
  <testcase classname="testExample.Add_CustomerTest" name="LnameField" time="0.001">
    <skipped/>
  </testcase> <!-- LnameField -->
  <testcase classname="testExample.Add_CustomerTest" name="LnameField" time="0.000">
    <skipped/>
  </testcase> <!-- LnameField -->
  <testcase classname="testExample.Add_CustomerTest" name="LnameField" time="0.001">
    <skipped/>
  </testcase> <!-- LnameField -->
  <testcase classname="testExample.Add_CustomerTest" name="LnameField" time="0.000">
    <skipped/>
  </testcase> <!-- LnameField -->
</testsuite> <!-- testExample.Add_CustomerTest -->
